const DESK=[{
    title: 'System',
    words: {
      'Maple':'',
      'FreeBSD':'',
      'Android':'',
      'ComGame_Sys':'',
      'iOS':'',
      'Linux':'',
      'MAC':'',
      'NetSecurity':'',
      'Windows':'',
      'WindowsPhone':'',
      'WinNT':''
    }
  },{
    title: 'DigitalTech',
    words: {
      'Blind_Mobile':'',
      'BlackBerry':'',
      'TechHistory':'',
      'Audiophile':'',
      'Bluetooth':'',
      'CDMA':'',
      'Headphone':'',
      'iPod':'',
      'MobileComm':'',
      'mobilesales':'',
      'Sony-style':'',
      'VoIP':'',
      'Broad_Band':'',
      'Fix-Network':'',
      'MOD_AP':'',
      'Digitalhome':'',
      'EDR':'',
      'VR':'',
      'DC':'',
      'DC_SALE':'',
      'DSLR':'',
      'Lomo':'',
      'PhotoEdit':''
    }
  }
  ,
  {
    title: 'DigitalWare',
    words: {
      'Array':'',
      'Liu':'',
      'AntiVirus':'',
      'AudioPlayer':'',
      'AVEncode':'',
      'Browsers':'',
      'Cad_Cae':'',
      'Digital_Art':'',
      'Dist-Com':'',
      'EzHotKey':'',
      'EZsoft':'',
      'Final-Cut':'',
      'FTP':'',
      'IME':'',
      'Instant_Mess':'',
      'Office':'',
      'P2PSoftWare':'',
      'Trace':'',
      'AppsForBBS':'',
      'Editor':'',
      'Cloud':''
    }
  }
  ,
  {
    title: 'CompScience',
    words: {
      'CodeJob':'',
      'PLT':'',
      'Prob_Solve':'',
      'Eclipse':'',
      'Flash':'',
      'LaTeX':'',
      'Fortran':'',
      'R_Language':'',
      'Ajax':'',
      'AndroidDev':'',
      'ASM':'',
      'C_and_CPP':'',
      'C_Sharp':'',
      'java':'',
      'Mathematica':'',
      'MATLAB':'',
      'OOAD':'',
      'Perl':'',
      'PHP':'',
      'Programming':'',
      'Python':'',
      'RegExp':'',
      'Ruby':'',
      'Visual_Basic':'',
      'LinuxDev':'',
      'MacDev':'',
      'CSSE':'',
      'DataScience':'',
      'Network_Sim':'',
      'Silverlight':'',
      'Database':'',
      'CompBook':'',
      'IPv6':'',
      'Network':'',
      'Web_Design':'',
      'Translate-CS':''
    }
  }
  ,
  {
    title:'Life_job',
    words:{
      'Tech_Job':'',
      'Soft_Job':''
    }
  }
];
var BarButtons=['about PTT','PTT wikipedia','about author','Login'];
